package com.mtbs3d.minecrift.tweaker.asm.handler;

import java.util.Iterator;

import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;

import com.mtbs3d.minecrift.tweaker.asm.ASMClassHandler;
import com.mtbs3d.minecrift.tweaker.asm.ASMMethodHandler;
import com.mtbs3d.minecrift.tweaker.asm.ASMUtil;
import com.mtbs3d.minecrift.tweaker.asm.ClassTuple;
import com.mtbs3d.minecrift.tweaker.asm.MethodTuple;

import static org.objectweb.asm.Opcodes.*;

public class ASMHandlerItemRendererFix extends ASMClassHandler {
	@Override
	public ClassTuple getDesiredClass() {
		return new ClassTuple("net.minecraft.client.renderer.ItemRenderer", "bly");
	}

	@Override
	public ASMMethodHandler[] getMethodHandlers() {
		return new ASMMethodHandler[]{};
	}

	@Override
	public boolean getComputeFrames() {
		return true;
	}

	@Override
	protected void patchClass(ClassNode node, boolean obfuscated) {
		if (ASMUtil.deleteMethod(node, new MethodTuple("func_78443_a", "(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/item/ItemStack;I)V", "a", "(Lsv;Ladd;I)V"))) {
			System.out.println("Deleted old renderItem");
		}
		{
			MethodVisitor mv = node.visitMethod(ACC_PUBLIC, obfuscated ? "a" : "func_78443_a", obfuscated ? "(Lsv;Ladd;I)V" : "(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/item/ItemStack;I)V", null, null);
			mv.visitCode();
			Label l0 = new Label();
			mv.visitLabel(l0);
			mv.visitLineNumber(66, l0);
			mv.visitVarInsn(ALOAD, 0);
			mv.visitVarInsn(ALOAD, 1);
			mv.visitVarInsn(ALOAD, 2);
			mv.visitVarInsn(ILOAD, 3);
			mv.visitFieldInsn(GETSTATIC, "net/minecraftforge/client/IItemRenderer$ItemRenderType", "EQUIPPED", "Lnet/minecraftforge/client/IItemRenderer$ItemRenderType;");
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/ItemRenderer", "renderItem", "(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/item/ItemStack;ILnet/minecraftforge/client/IItemRenderer$ItemRenderType;)V", false);
			Label l1 = new Label();
			mv.visitLabel(l1);
			mv.visitLineNumber(67, l1);
			mv.visitInsn(RETURN);
			Label l2 = new Label();
			mv.visitLabel(l2);
			mv.visitLocalVariable("this", obfuscated ? "Lbly;" : "Lnet/minecraft/client/renderer/ItemRenderer;", null, l0, l2, 0);
			mv.visitLocalVariable("p_78443_1_", obfuscated ? "Lsv;" : "Lnet/minecraft/entity/EntityLivingBase;", null, l0, l2, 1);
			mv.visitLocalVariable("p_78443_2_", obfuscated ? "Ladd;" : "Lnet/minecraft/item/ItemStack;", null, l0, l2, 2);
			mv.visitLocalVariable("p_78443_3_", "I", null, l0, l2, 3);
			mv.visitMaxs(5, 4);
			mv.visitEnd();
			System.out.println("Injected new renderItem");
		}
		{
			MethodVisitor mv = node.visitMethod(ACC_PUBLIC, "renderItem", "(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/item/ItemStack;ILnet/minecraftforge/client/IItemRenderer$ItemRenderType;)V", null, null);
			mv.visitCode();
			Label l0 = new Label();
			mv.visitLabel(l0);
			mv.visitLineNumber(71, l0);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glPushMatrix", "()V", false);
			Label l1 = new Label();
			mv.visitLabel(l1);
			mv.visitLineNumber(72, l1);
			mv.visitVarInsn(ALOAD, 0);
			mv.visitFieldInsn(GETFIELD, "net/minecraft/client/renderer/ItemRenderer", "field_78455_a", "Lnet/minecraft/client/Minecraft;");
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/Minecraft", "func_110434_K", "()Lnet/minecraft/client/renderer/texture/TextureManager;", false);
			mv.visitVarInsn(ASTORE, 5);
			Label l2 = new Label();
			mv.visitLabel(l2);
			mv.visitLineNumber(73, l2);
			mv.visitVarInsn(ALOAD, 2);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/item/ItemStack", "func_77973_b", "()Lnet/minecraft/item/Item;", false);
			mv.visitVarInsn(ASTORE, 6);
			Label l3 = new Label();
			mv.visitLabel(l3);
			mv.visitLineNumber(74, l3);
			mv.visitVarInsn(ALOAD, 6);
			mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/block/Block", "func_149634_a", "(Lnet/minecraft/item/Item;)Lnet/minecraft/block/Block;", false);
			mv.visitVarInsn(ASTORE, 7);
			Label l4 = new Label();
			mv.visitLabel(l4);
			mv.visitLineNumber(76, l4);
			mv.visitVarInsn(ALOAD, 2);
			Label l5 = new Label();
			mv.visitJumpInsn(IFNULL, l5);
			mv.visitVarInsn(ALOAD, 7);
			mv.visitJumpInsn(IFNULL, l5);
			mv.visitVarInsn(ALOAD, 7);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/block/Block", "func_149701_w", "()I", false);
			mv.visitJumpInsn(IFEQ, l5);
			Label l6 = new Label();
			mv.visitLabel(l6);
			mv.visitLineNumber(78, l6);
			mv.visitIntInsn(SIPUSH, 3042);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glEnable", "(I)V", false);
			Label l7 = new Label();
			mv.visitLabel(l7);
			mv.visitLineNumber(79, l7);
			mv.visitIntInsn(SIPUSH, 2884);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glEnable", "(I)V", false);
			Label l8 = new Label();
			mv.visitLabel(l8);
			mv.visitLineNumber(80, l8);
			mv.visitIntInsn(SIPUSH, 770);
			mv.visitIntInsn(SIPUSH, 771);
			mv.visitInsn(ICONST_1);
			mv.visitInsn(ICONST_0);
			mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/OpenGlHelper", "func_148821_a", "(IIII)V", false);
			mv.visitLabel(l5);
			mv.visitLineNumber(82, l5);
			mv.visitFrame(Opcodes.F_APPEND,3, new Object[] {"net/minecraft/client/renderer/texture/TextureManager", "net/minecraft/item/Item", "net/minecraft/block/Block"}, 0, null);
			mv.visitVarInsn(ALOAD, 2);
			mv.visitVarInsn(ALOAD, 4);
			mv.visitMethodInsn(INVOKESTATIC, "net/minecraftforge/client/MinecraftForgeClient", "getItemRenderer", "(Lnet/minecraft/item/ItemStack;Lnet/minecraftforge/client/IItemRenderer$ItemRenderType;)Lnet/minecraftforge/client/IItemRenderer;", false);
			mv.visitVarInsn(ASTORE, 8);
			Label l9 = new Label();
			mv.visitLabel(l9);
			mv.visitLineNumber(83, l9);
			mv.visitVarInsn(ALOAD, 8);
			Label l10 = new Label();
			mv.visitJumpInsn(IFNULL, l10);
			Label l11 = new Label();
			mv.visitLabel(l11);
			mv.visitLineNumber(85, l11);
			mv.visitVarInsn(ALOAD, 5);
			mv.visitVarInsn(ALOAD, 5);
			mv.visitVarInsn(ALOAD, 2);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/item/ItemStack", "func_94608_d", "()I", false);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureManager", "func_130087_a", "(I)Lnet/minecraft/util/ResourceLocation;", false);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureManager", "func_110577_a", "(Lnet/minecraft/util/ResourceLocation;)V", false);
			Label l12 = new Label();
			mv.visitLabel(l12);
			mv.visitLineNumber(86, l12);
			mv.visitVarInsn(ALOAD, 4);
			mv.visitVarInsn(ALOAD, 8);
			mv.visitVarInsn(ALOAD, 0);
			mv.visitFieldInsn(GETFIELD, "net/minecraft/client/renderer/ItemRenderer", "field_147720_h", "Lnet/minecraft/client/renderer/RenderBlocks;");
			mv.visitVarInsn(ALOAD, 1);
			mv.visitVarInsn(ALOAD, 2);
			mv.visitMethodInsn(INVOKESTATIC, "net/minecraftforge/client/ForgeHooksClient", "renderEquippedItem", "(Lnet/minecraftforge/client/IItemRenderer$ItemRenderType;Lnet/minecraftforge/client/IItemRenderer;Lnet/minecraft/client/renderer/RenderBlocks;Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/item/ItemStack;)V", false);
			Label l13 = new Label();
			mv.visitJumpInsn(GOTO, l13);
			mv.visitLabel(l10);
			mv.visitLineNumber(89, l10);
			mv.visitFrame(Opcodes.F_APPEND,1, new Object[] {"net/minecraftforge/client/IItemRenderer"}, 0, null);
			mv.visitVarInsn(ALOAD, 2);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/item/ItemStack", "func_94608_d", "()I", false);
			Label l14 = new Label();
			mv.visitJumpInsn(IFNE, l14);
			mv.visitVarInsn(ALOAD, 6);
			mv.visitTypeInsn(INSTANCEOF, "net/minecraft/item/ItemBlock");
			mv.visitJumpInsn(IFEQ, l14);
			mv.visitVarInsn(ALOAD, 7);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/block/Block", "func_149645_b", "()I", false);
			mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/RenderBlocks", "func_147739_a", "(I)Z", false);
			mv.visitJumpInsn(IFEQ, l14);
			Label l15 = new Label();
			mv.visitLabel(l15);
			mv.visitLineNumber(91, l15);
			mv.visitVarInsn(ALOAD, 5);
			mv.visitVarInsn(ALOAD, 5);
			mv.visitInsn(ICONST_0);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureManager", "func_130087_a", "(I)Lnet/minecraft/util/ResourceLocation;", false);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureManager", "func_110577_a", "(Lnet/minecraft/util/ResourceLocation;)V", false);
			Label l16 = new Label();
			mv.visitLabel(l16);
			mv.visitLineNumber(93, l16);
			mv.visitVarInsn(ALOAD, 2);
			Label l17 = new Label();
			mv.visitJumpInsn(IFNULL, l17);
			mv.visitVarInsn(ALOAD, 7);
			mv.visitJumpInsn(IFNULL, l17);
			mv.visitVarInsn(ALOAD, 7);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/block/Block", "func_149701_w", "()I", false);
			mv.visitJumpInsn(IFEQ, l17);
			Label l18 = new Label();
			mv.visitLabel(l18);
			mv.visitLineNumber(95, l18);
			mv.visitInsn(ICONST_0);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDepthMask", "(Z)V", false);
			Label l19 = new Label();
			mv.visitLabel(l19);
			mv.visitLineNumber(96, l19);
			mv.visitVarInsn(ALOAD, 0);
			mv.visitFieldInsn(GETFIELD, "net/minecraft/client/renderer/ItemRenderer", "field_147720_h", "Lnet/minecraft/client/renderer/RenderBlocks;");
			mv.visitVarInsn(ALOAD, 7);
			mv.visitVarInsn(ALOAD, 2);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/item/ItemStack", "func_77960_j", "()I", false);
			mv.visitInsn(FCONST_1);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/RenderBlocks", "func_147800_a", "(Lnet/minecraft/block/Block;IF)V", false);
			Label l20 = new Label();
			mv.visitLabel(l20);
			mv.visitLineNumber(97, l20);
			mv.visitInsn(ICONST_1);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDepthMask", "(Z)V", false);
			mv.visitJumpInsn(GOTO, l13);
			mv.visitLabel(l17);
			mv.visitLineNumber(101, l17);
			mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
			mv.visitVarInsn(ALOAD, 0);
			mv.visitFieldInsn(GETFIELD, "net/minecraft/client/renderer/ItemRenderer", "field_147720_h", "Lnet/minecraft/client/renderer/RenderBlocks;");
			mv.visitVarInsn(ALOAD, 7);
			mv.visitVarInsn(ALOAD, 2);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/item/ItemStack", "func_77960_j", "()I", false);
			mv.visitInsn(FCONST_1);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/RenderBlocks", "func_147800_a", "(Lnet/minecraft/block/Block;IF)V", false);
			mv.visitJumpInsn(GOTO, l13);
			mv.visitLabel(l14);
			mv.visitLineNumber(106, l14);
			mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
			mv.visitVarInsn(ALOAD, 1);
			mv.visitVarInsn(ALOAD, 2);
			mv.visitVarInsn(ILOAD, 3);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/EntityLivingBase", "func_70620_b", "(Lnet/minecraft/item/ItemStack;I)Lnet/minecraft/util/IIcon;", false);
			mv.visitVarInsn(ASTORE, 9);
			Label l21 = new Label();
			mv.visitLabel(l21);
			mv.visitLineNumber(108, l21);
			mv.visitVarInsn(ALOAD, 9);
			Label l22 = new Label();
			mv.visitJumpInsn(IFNONNULL, l22);
			Label l23 = new Label();
			mv.visitLabel(l23);
			mv.visitLineNumber(110, l23);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glPopMatrix", "()V", false);
			Label l24 = new Label();
			mv.visitLabel(l24);
			mv.visitLineNumber(111, l24);
			mv.visitInsn(RETURN);
			mv.visitLabel(l22);
			mv.visitLineNumber(114, l22);
			mv.visitFrame(Opcodes.F_APPEND,1, new Object[] {"net/minecraft/util/IIcon"}, 0, null);
			mv.visitVarInsn(ALOAD, 5);
			mv.visitVarInsn(ALOAD, 5);
			mv.visitVarInsn(ALOAD, 2);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/item/ItemStack", "func_94608_d", "()I", false);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureManager", "func_130087_a", "(I)Lnet/minecraft/util/ResourceLocation;", false);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureManager", "func_110577_a", "(Lnet/minecraft/util/ResourceLocation;)V", false);
			Label l25 = new Label();
			mv.visitLabel(l25);
			mv.visitLineNumber(115, l25);
			mv.visitInsn(ICONST_0);
			mv.visitInsn(ICONST_0);
			mv.visitInsn(FCONST_1);
			mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/texture/TextureUtil", "func_152777_a", "(ZZF)V", false);
			Label l26 = new Label();
			mv.visitLabel(l26);
			mv.visitLineNumber(116, l26);
			mv.visitFieldInsn(GETSTATIC, "net/minecraft/client/renderer/Tessellator", "field_78398_a", "Lnet/minecraft/client/renderer/Tessellator;");
			mv.visitVarInsn(ASTORE, 10);
			Label l27 = new Label();
			mv.visitLabel(l27);
			mv.visitLineNumber(117, l27);
			mv.visitVarInsn(ALOAD, 9);
			mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/util/IIcon", "func_94209_e", "()F", true);
			mv.visitVarInsn(FSTORE, 11);
			Label l28 = new Label();
			mv.visitLabel(l28);
			mv.visitLineNumber(118, l28);
			mv.visitVarInsn(ALOAD, 9);
			mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/util/IIcon", "func_94212_f", "()F", true);
			mv.visitVarInsn(FSTORE, 12);
			Label l29 = new Label();
			mv.visitLabel(l29);
			mv.visitLineNumber(119, l29);
			mv.visitVarInsn(ALOAD, 9);
			mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/util/IIcon", "func_94206_g", "()F", true);
			mv.visitVarInsn(FSTORE, 13);
			Label l30 = new Label();
			mv.visitLabel(l30);
			mv.visitLineNumber(120, l30);
			mv.visitVarInsn(ALOAD, 9);
			mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/util/IIcon", "func_94210_h", "()F", true);
			mv.visitVarInsn(FSTORE, 14);
			Label l31 = new Label();
			mv.visitLabel(l31);
			mv.visitLineNumber(121, l31);
			mv.visitInsn(FCONST_0);
			mv.visitVarInsn(FSTORE, 15);
			Label l32 = new Label();
			mv.visitLabel(l32);
			mv.visitLineNumber(122, l32);
			mv.visitLdcInsn(new Float("0.3"));
			mv.visitVarInsn(FSTORE, 16);
			Label l33 = new Label();
			mv.visitLabel(l33);
			mv.visitLineNumber(123, l33);
			mv.visitLdcInsn(new Integer(32826));
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glEnable", "(I)V", false);
			Label l34 = new Label();
			mv.visitLabel(l34);
			mv.visitLineNumber(124, l34);
			mv.visitVarInsn(FLOAD, 15);
			mv.visitInsn(FNEG);
			mv.visitVarInsn(FLOAD, 16);
			mv.visitInsn(FNEG);
			mv.visitInsn(FCONST_0);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glTranslatef", "(FFF)V", false);
			Label l35 = new Label();
			mv.visitLabel(l35);
			mv.visitLineNumber(125, l35);
			mv.visitLdcInsn(new Float("1.5"));
			mv.visitVarInsn(FSTORE, 17);
			Label l36 = new Label();
			mv.visitLabel(l36);
			mv.visitLineNumber(126, l36);
			mv.visitVarInsn(FLOAD, 17);
			mv.visitVarInsn(FLOAD, 17);
			mv.visitVarInsn(FLOAD, 17);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glScalef", "(FFF)V", false);
			Label l37 = new Label();
			mv.visitLabel(l37);
			mv.visitLineNumber(127, l37);
			mv.visitLdcInsn(new Float("50.0"));
			mv.visitInsn(FCONST_0);
			mv.visitInsn(FCONST_1);
			mv.visitInsn(FCONST_0);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glRotatef", "(FFFF)V", false);
			Label l38 = new Label();
			mv.visitLabel(l38);
			mv.visitLineNumber(128, l38);
			mv.visitLdcInsn(new Float("335.0"));
			mv.visitInsn(FCONST_0);
			mv.visitInsn(FCONST_0);
			mv.visitInsn(FCONST_1);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glRotatef", "(FFFF)V", false);
			Label l39 = new Label();
			mv.visitLabel(l39);
			mv.visitLineNumber(129, l39);
			mv.visitLdcInsn(new Float("-0.9375"));
			mv.visitLdcInsn(new Float("-0.0625"));
			mv.visitInsn(FCONST_0);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glTranslatef", "(FFF)V", false);
			Label l40 = new Label();
			mv.visitLabel(l40);
			mv.visitLineNumber(130, l40);
			mv.visitVarInsn(ALOAD, 10);
			mv.visitVarInsn(FLOAD, 12);
			mv.visitVarInsn(FLOAD, 13);
			mv.visitVarInsn(FLOAD, 11);
			mv.visitVarInsn(FLOAD, 14);
			mv.visitVarInsn(ALOAD, 9);
			mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/util/IIcon", "func_94211_a", "()I", true);
			mv.visitVarInsn(ALOAD, 9);
			mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/util/IIcon", "func_94216_b", "()I", true);
			mv.visitLdcInsn(new Float("0.0625"));
			mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/ItemRenderer", "func_78439_a", "(Lnet/minecraft/client/renderer/Tessellator;FFFFIIF)V", false);
			Label l41 = new Label();
			mv.visitLabel(l41);
			mv.visitLineNumber(132, l41);
			mv.visitVarInsn(ALOAD, 2);
			mv.visitVarInsn(ILOAD, 3);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/item/ItemStack", "func_77962_s", "(I)Z", false);
			Label l42 = new Label();
			mv.visitJumpInsn(IFEQ, l42);
			Label l43 = new Label();
			mv.visitLabel(l43);
			mv.visitLineNumber(134, l43);
			mv.visitIntInsn(SIPUSH, 514);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDepthFunc", "(I)V", false);
			Label l44 = new Label();
			mv.visitLabel(l44);
			mv.visitLineNumber(135, l44);
			mv.visitIntInsn(SIPUSH, 2896);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDisable", "(I)V", false);
			Label l45 = new Label();
			mv.visitLabel(l45);
			mv.visitLineNumber(136, l45);
			mv.visitVarInsn(ALOAD, 5);
			mv.visitFieldInsn(GETSTATIC, "net/minecraft/client/renderer/ItemRenderer", "field_110930_b", "Lnet/minecraft/util/ResourceLocation;");
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureManager", "func_110577_a", "(Lnet/minecraft/util/ResourceLocation;)V", false);
			Label l46 = new Label();
			mv.visitLabel(l46);
			mv.visitLineNumber(137, l46);
			mv.visitIntInsn(SIPUSH, 3042);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glEnable", "(I)V", false);
			Label l47 = new Label();
			mv.visitLabel(l47);
			mv.visitLineNumber(138, l47);
			mv.visitIntInsn(SIPUSH, 768);
			mv.visitInsn(ICONST_1);
			mv.visitInsn(ICONST_1);
			mv.visitInsn(ICONST_0);
			mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/OpenGlHelper", "func_148821_a", "(IIII)V", false);
			Label l48 = new Label();
			mv.visitLabel(l48);
			mv.visitLineNumber(139, l48);
			mv.visitLdcInsn(new Float("0.76"));
			mv.visitVarInsn(FSTORE, 18);
			Label l49 = new Label();
			mv.visitLabel(l49);
			mv.visitLineNumber(140, l49);
			mv.visitLdcInsn(new Float("0.5"));
			mv.visitVarInsn(FLOAD, 18);
			mv.visitInsn(FMUL);
			mv.visitLdcInsn(new Float("0.25"));
			mv.visitVarInsn(FLOAD, 18);
			mv.visitInsn(FMUL);
			mv.visitLdcInsn(new Float("0.8"));
			mv.visitVarInsn(FLOAD, 18);
			mv.visitInsn(FMUL);
			mv.visitInsn(FCONST_1);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glColor4f", "(FFFF)V", false);
			Label l50 = new Label();
			mv.visitLabel(l50);
			mv.visitLineNumber(141, l50);
			mv.visitIntInsn(SIPUSH, 5890);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glMatrixMode", "(I)V", false);
			Label l51 = new Label();
			mv.visitLabel(l51);
			mv.visitLineNumber(142, l51);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glPushMatrix", "()V", false);
			Label l52 = new Label();
			mv.visitLabel(l52);
			mv.visitLineNumber(143, l52);
			mv.visitLdcInsn(new Float("0.125"));
			mv.visitVarInsn(FSTORE, 19);
			Label l53 = new Label();
			mv.visitLabel(l53);
			mv.visitLineNumber(144, l53);
			mv.visitVarInsn(FLOAD, 19);
			mv.visitVarInsn(FLOAD, 19);
			mv.visitVarInsn(FLOAD, 19);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glScalef", "(FFF)V", false);
			Label l54 = new Label();
			mv.visitLabel(l54);
			mv.visitLineNumber(145, l54);
			mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/Minecraft", "func_71386_F", "()J", false);
			mv.visitLdcInsn(new Long(3000L));
			mv.visitInsn(LREM);
			mv.visitInsn(L2F);
			mv.visitLdcInsn(new Float("3000.0"));
			mv.visitInsn(FDIV);
			mv.visitLdcInsn(new Float("8.0"));
			mv.visitInsn(FMUL);
			mv.visitVarInsn(FSTORE, 20);
			Label l55 = new Label();
			mv.visitLabel(l55);
			mv.visitLineNumber(146, l55);
			mv.visitVarInsn(FLOAD, 20);
			mv.visitInsn(FCONST_0);
			mv.visitInsn(FCONST_0);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glTranslatef", "(FFF)V", false);
			Label l56 = new Label();
			mv.visitLabel(l56);
			mv.visitLineNumber(147, l56);
			mv.visitLdcInsn(new Float("-50.0"));
			mv.visitInsn(FCONST_0);
			mv.visitInsn(FCONST_0);
			mv.visitInsn(FCONST_1);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glRotatef", "(FFFF)V", false);
			Label l57 = new Label();
			mv.visitLabel(l57);
			mv.visitLineNumber(148, l57);
			mv.visitVarInsn(ALOAD, 10);
			mv.visitInsn(FCONST_0);
			mv.visitInsn(FCONST_0);
			mv.visitInsn(FCONST_1);
			mv.visitInsn(FCONST_1);
			mv.visitIntInsn(SIPUSH, 256);
			mv.visitIntInsn(SIPUSH, 256);
			mv.visitLdcInsn(new Float("0.0625"));
			mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/ItemRenderer", "func_78439_a", "(Lnet/minecraft/client/renderer/Tessellator;FFFFIIF)V", false);
			Label l58 = new Label();
			mv.visitLabel(l58);
			mv.visitLineNumber(149, l58);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glPopMatrix", "()V", false);
			Label l59 = new Label();
			mv.visitLabel(l59);
			mv.visitLineNumber(150, l59);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glPushMatrix", "()V", false);
			Label l60 = new Label();
			mv.visitLabel(l60);
			mv.visitLineNumber(151, l60);
			mv.visitVarInsn(FLOAD, 19);
			mv.visitVarInsn(FLOAD, 19);
			mv.visitVarInsn(FLOAD, 19);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glScalef", "(FFF)V", false);
			Label l61 = new Label();
			mv.visitLabel(l61);
			mv.visitLineNumber(152, l61);
			mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/Minecraft", "func_71386_F", "()J", false);
			mv.visitLdcInsn(new Long(4873L));
			mv.visitInsn(LREM);
			mv.visitInsn(L2F);
			mv.visitLdcInsn(new Float("4873.0"));
			mv.visitInsn(FDIV);
			mv.visitLdcInsn(new Float("8.0"));
			mv.visitInsn(FMUL);
			mv.visitVarInsn(FSTORE, 20);
			Label l62 = new Label();
			mv.visitLabel(l62);
			mv.visitLineNumber(153, l62);
			mv.visitVarInsn(FLOAD, 20);
			mv.visitInsn(FNEG);
			mv.visitInsn(FCONST_0);
			mv.visitInsn(FCONST_0);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glTranslatef", "(FFF)V", false);
			Label l63 = new Label();
			mv.visitLabel(l63);
			mv.visitLineNumber(154, l63);
			mv.visitLdcInsn(new Float("10.0"));
			mv.visitInsn(FCONST_0);
			mv.visitInsn(FCONST_0);
			mv.visitInsn(FCONST_1);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glRotatef", "(FFFF)V", false);
			Label l64 = new Label();
			mv.visitLabel(l64);
			mv.visitLineNumber(155, l64);
			mv.visitVarInsn(ALOAD, 10);
			mv.visitInsn(FCONST_0);
			mv.visitInsn(FCONST_0);
			mv.visitInsn(FCONST_1);
			mv.visitInsn(FCONST_1);
			mv.visitIntInsn(SIPUSH, 256);
			mv.visitIntInsn(SIPUSH, 256);
			mv.visitLdcInsn(new Float("0.0625"));
			mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/ItemRenderer", "func_78439_a", "(Lnet/minecraft/client/renderer/Tessellator;FFFFIIF)V", false);
			Label l65 = new Label();
			mv.visitLabel(l65);
			mv.visitLineNumber(156, l65);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glPopMatrix", "()V", false);
			Label l66 = new Label();
			mv.visitLabel(l66);
			mv.visitLineNumber(157, l66);
			mv.visitIntInsn(SIPUSH, 5888);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glMatrixMode", "(I)V", false);
			Label l67 = new Label();
			mv.visitLabel(l67);
			mv.visitLineNumber(158, l67);
			mv.visitIntInsn(SIPUSH, 3042);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDisable", "(I)V", false);
			Label l68 = new Label();
			mv.visitLabel(l68);
			mv.visitLineNumber(159, l68);
			mv.visitIntInsn(SIPUSH, 2896);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glEnable", "(I)V", false);
			Label l69 = new Label();
			mv.visitLabel(l69);
			mv.visitLineNumber(160, l69);
			mv.visitIntInsn(SIPUSH, 515);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDepthFunc", "(I)V", false);
			mv.visitLabel(l42);
			mv.visitLineNumber(163, l42);
			mv.visitFrame(Opcodes.F_FULL, 18, new Object[] {"net/minecraft/client/renderer/ItemRenderer", "net/minecraft/entity/EntityLivingBase", "net/minecraft/item/ItemStack", Opcodes.INTEGER, "net/minecraftforge/client/IItemRenderer$ItemRenderType", "net/minecraft/client/renderer/texture/TextureManager", "net/minecraft/item/Item", "net/minecraft/block/Block", "net/minecraftforge/client/IItemRenderer", "net/minecraft/util/IIcon", "net/minecraft/client/renderer/Tessellator", Opcodes.FLOAT, Opcodes.FLOAT, Opcodes.FLOAT, Opcodes.FLOAT, Opcodes.FLOAT, Opcodes.FLOAT, Opcodes.FLOAT}, 0, new Object[] {});
			mv.visitLdcInsn(new Integer(32826));
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDisable", "(I)V", false);
			Label l70 = new Label();
			mv.visitLabel(l70);
			mv.visitLineNumber(164, l70);
			mv.visitVarInsn(ALOAD, 5);
			mv.visitVarInsn(ALOAD, 5);
			mv.visitVarInsn(ALOAD, 2);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/item/ItemStack", "func_94608_d", "()I", false);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureManager", "func_130087_a", "(I)Lnet/minecraft/util/ResourceLocation;", false);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureManager", "func_110577_a", "(Lnet/minecraft/util/ResourceLocation;)V", false);
			Label l71 = new Label();
			mv.visitLabel(l71);
			mv.visitLineNumber(165, l71);
			mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/texture/TextureUtil", "func_147945_b", "()V", false);
			mv.visitLabel(l13);
			mv.visitLineNumber(168, l13);
			mv.visitFrame(Opcodes.F_FULL, 9, new Object[] {"net/minecraft/client/renderer/ItemRenderer", "net/minecraft/entity/EntityLivingBase", "net/minecraft/item/ItemStack", Opcodes.INTEGER, "net/minecraftforge/client/IItemRenderer$ItemRenderType", "net/minecraft/client/renderer/texture/TextureManager", "net/minecraft/item/Item", "net/minecraft/block/Block", "net/minecraftforge/client/IItemRenderer"}, 0, new Object[] {});
			mv.visitVarInsn(ALOAD, 2);
			Label l72 = new Label();
			mv.visitJumpInsn(IFNULL, l72);
			mv.visitVarInsn(ALOAD, 7);
			mv.visitJumpInsn(IFNULL, l72);
			mv.visitVarInsn(ALOAD, 7);
			mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/block/Block", "func_149701_w", "()I", false);
			mv.visitJumpInsn(IFEQ, l72);
			Label l73 = new Label();
			mv.visitLabel(l73);
			mv.visitLineNumber(170, l73);
			mv.visitIntInsn(SIPUSH, 3042);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDisable", "(I)V", false);
			mv.visitLabel(l72);
			mv.visitLineNumber(173, l72);
			mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glPopMatrix", "()V", false);
			Label l74 = new Label();
			mv.visitLabel(l74);
			mv.visitLineNumber(174, l74);
			mv.visitInsn(RETURN);
			Label l75 = new Label();
			mv.visitLabel(l75);
			mv.visitLocalVariable("f7", "F", null, l49, l42, 18);
			mv.visitLocalVariable("f8", "F", null, l53, l42, 19);
			mv.visitLocalVariable("f9", "F", null, l55, l42, 20);
			mv.visitLocalVariable("iicon", "Lnet/minecraft/util/IIcon;", null, l21, l13, 9);
			mv.visitLocalVariable("tessellator", "Lnet/minecraft/client/renderer/Tessellator;", null, l27, l13, 10);
			mv.visitLocalVariable("f", "F", null, l28, l13, 11);
			mv.visitLocalVariable("f1", "F", null, l29, l13, 12);
			mv.visitLocalVariable("f2", "F", null, l30, l13, 13);
			mv.visitLocalVariable("f3", "F", null, l31, l13, 14);
			mv.visitLocalVariable("f4", "F", null, l32, l13, 15);
			mv.visitLocalVariable("f5", "F", null, l33, l13, 16);
			mv.visitLocalVariable("f6", "F", null, l36, l13, 17);
			mv.visitLocalVariable("this", "Lnet/minecraft/client/renderer/ItemRenderer;", null, l0, l75, 0);
			mv.visitLocalVariable("p_78443_1_", "Lnet/minecraft/entity/EntityLivingBase;", null, l0, l75, 1);
			mv.visitLocalVariable("p_78443_2_", "Lnet/minecraft/item/ItemStack;", null, l0, l75, 2);
			mv.visitLocalVariable("p_78443_3_", "I", null, l0, l75, 3);
			mv.visitLocalVariable("type", "Lnet/minecraftforge/client/IItemRenderer$ItemRenderType;", null, l0, l75, 4);
			mv.visitLocalVariable("texturemanager", "Lnet/minecraft/client/renderer/texture/TextureManager;", null, l2, l75, 5);
			mv.visitLocalVariable("item", "Lnet/minecraft/item/Item;", null, l3, l75, 6);
			mv.visitLocalVariable("block", "Lnet/minecraft/block/Block;", null, l4, l75, 7);
			mv.visitLocalVariable("customRenderer", "Lnet/minecraftforge/client/IItemRenderer;", null, l9, l75, 8);
			mv.visitMaxs(8, 21);
			mv.visitEnd();
			System.out.println("Injected Forge renderItem");
		}
	}

	/*public static class MethodHandler implements ASMMethodHandler {
		@Override
		public MethodTuple getDesiredMethod() {
			return new MethodTuple("renderItem", "(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/item/ItemStack;I)V", "a", "(Lsv;Ladd;I)V");
		}

		@Override
		public void patchMethod(MethodNode methodNode, ClassNode classNode, boolean obfuscated) {
			for (int i = 0; i < methodNode.instructions.size(); i++) {
				AbstractInsnNode insn = methodNode.instructions.get(i);
				if (insn instanceof MethodInsnNode) {
					MethodInsnNode insn2 = (MethodInsnNode)insn;
				}
			}
		}
	}*/
}
